# Generated by Django 4.2.19 on 2025-02-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_addes', models.DateTimeField(auto_now_add=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_websites.bean')),
            ],
        ),
    ]
