# Generated by Django 4.2.19 on 2025-02-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_websites', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_addes',
            new_name='date_added',
        ),
    ]
